# Generated by Django 4.2.1 on 2023-07-06 01:02
#to create superuser initially 
# whenever there are changes in databases then migrations should be done to apply those and give details about them in here
# migrate command is used to run these changes in database
#(python manage.py sqlmigrate blog 0001) is used to check the sql commands used to make below changes in database
#defaultly django uses Sqlite , django uses model classes which functions as ORM(object relational mappers) which brings down burden to write sql quiries to create and work with databases

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
